name: QA Agent

on:
  workflow_call:
    inputs:
      reasoning_model:
        required: true
        type: string
      target_branch:
        required: true
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  run-agent:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install git
      run: |
        apt-get update
        apt-get install -y git

    - name: Download GitHub MCP Binary
      run: |
          curl -L -o github-mcp-server.tar.gz https://github.com/github/github-mcp-server/releases/download/v0.31.0/github-mcp-server_Linux_x86_64.tar.gz
          tar -xzf github-mcp-server.tar.gz
          chmod +x github-mcp-server

    - name: Install agent
      run: pip install git+https://github.com/jvictor96/qa-agent@main

    - name: Run agent
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REASONING_MODEL: ${{ inputs.reasoning_model }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: run-agent